apiVersion: v1
kind: Secret
metadata:
  name: payment-db-credentials
  namespace: voltstore
type: Opaque
stringData:
  POSTGRES_USER: "payment-service"
  POSTGRES_PASSWORD: "payment-service"
  SPRING_DATASOURCE_USERNAME: "payment-service"
  SPRING_DATASOURCE_PASSWORD: "payment-service"