apiVersion: v1
kind: Service
metadata:
  name: order-service-postgres
  namespace: voltstore
spec:
  type: ClusterIP
  selector:
    app: order-service-postgres
  ports:
    - port: 5432
      targetPort: 5432