apiVersion: v1
kind: Secret
metadata:
  name: order-db-credentials
  namespace: voltstore
type: Opaque
stringData:
  POSTGRES_USER: "order-service"
  POSTGRES_PASSWORD: "order-service"
  SPRING_DATASOURCE_USERNAME: "order-service"
  SPRING_DATASOURCE_PASSWORD: "order-service"