apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: voltstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
      containers:
        - name: auth-service
          image: voltstore/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: auth-config
            - secretRef:
                name: auth-db-credentials
            - secretRef:
                name: auth-secrets
          resources:
            requests:
              cpu: 250m
              memory: 484Mi
            limits:
              cpu: "2"
              memory: 968Mi
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
