apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: voltstore
data:
  POSTGRES_DB: "auth-service"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://auth-service-postgres:5432/auth-service"
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -Xlog:gc*"
