apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: voltstore
type: Opaque
stringData:
  AUTH_JWT_SECRET: "change-me-local-dev-secret-at-least-32-bytes-long"
  AUTH_ADMIN_PASSWORD: "admin-local-password"
  AUTH_INTERNAL_TOKEN: "change-me-local-internal-token-at-least-32-chars"
