apiVersion: v1
kind: Secret
metadata:
  name: auth-db-credentials
  namespace: voltstore
type: Opaque
stringData:
  POSTGRES_USER: "auth-service"
  POSTGRES_PASSWORD: "auth-service"
  SPRING_DATASOURCE_USERNAME: "auth-service"
  SPRING_DATASOURCE_PASSWORD: "auth-service"