apiVersion: v1
kind: Secret
metadata:
  name: auth-db-credentials
  namespace: voltstore
type: Opaque
stringData:
  POSTGRES_USER: "auth-service"
  POSTGRES_PASSWORD: "auth-service"
  SPRING_DATASOURCE_USERNAME: "auth-service"
  SPRING_DATASOURCE_PASSWORD: "auth-service"
  JWT_SECRET: "change-me-local-dev-secret-at-least-32-bytes-long"
  ADMIN_EMAIL: "admin@voltstore.com"
  ADMIN_PASSWORD: "admin-local-password"
  INTERNAL_TOKEN: "change-me-local-internal-token-at-least-32-chars"