apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-config
  namespace: voltstore
data:
  POSTGRES_DB: "delivery-service"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://delivery-service-postgres:5432/delivery-service"
  JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70 -Xlog:gc*"
