apiVersion: v1
kind: Secret
metadata:
  name: delivery-db-credentials
  namespace: voltstore
type: Opaque
stringData:
  POSTGRES_USER: "delivery-service"
  POSTGRES_PASSWORD: "delivery-service"
  SPRING_DATASOURCE_USERNAME: "delivery-service"
  SPRING_DATASOURCE_PASSWORD: "delivery-service"