spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      probes:
        enabled: true

catalog:
  client:
    base-url: http://catalog-service:8080/api/v1/catalog/products