spring:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      probes:
        enabled: true

clients:
  catalog:
    url: http://catalog-service:8081