package ua.edu.ukma.springers.voltstore.catalog.entities;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Entity
@Table(name = "categories")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Category {
    public static final int NAME_MAX_LENGTH = 100;

    // Generated by Hibernate in the application (not by the database) when the entity is persisted
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    // Unique ignoring case: enforced by the categories_name_lower_key index (see V1 migration)
    @Column(nullable = false, length = NAME_MAX_LENGTH)
    private String name;

    public Category(String name) {
        this.name = name;
    }

    public void rename(String name) {
        this.name = name;
    }
}
