apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-postgres-pvc
  namespace: voltstore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service-postgres
  namespace: voltstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service-postgres
  template:
    metadata:
      labels:
        app: catalog-service-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: catalog-config
            - secretRef:
                name: catalog-db-credentials
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: catalog-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service-postgres
  namespace: voltstore
spec:
  type: ClusterIP
  selector:
    app: catalog-service-postgres
  ports:
    - port: 5432
      targetPort: 5432