apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog
spec:
  type: ClusterIP
  selector:
    app: catalog-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
